# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e1cjb3NJdACZNpgjb8KVaIL0OWFuHQgX
"""

import pandas as pd
import io

# 1. DATA CREATION (Simulating Solar Park Input)
# We create the 'raw' data directly in the script to ensure it runs easily.
csv_data = """timestamp,sensor_id,energy_kwh
2026-01-13 10:00,SOLAR_01,15.5
2026-01-13 10:05,SOLAR_01,-99.0
2026-01-13 10:10,SOLAR_01,16.2"""

# 2. EXTRACT
df = pd.read_csv(io.StringIO(csv_data))

# 3. TRANSFORM & DATA QUALITY ENFORCEMENT
# Removing erroneous -99.0 readings to ensure high-quality data for ML experts.
clean_df = df[df['energy_kwh'] >= 0].copy()

# 4. LOAD / OUTPUT
print("Successfully processed BayWa r.e. Solar Data:")
print(clean_df)